server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://61.167.120.133:3306/chargingpile?useSSL=true&characterEncoding=utf-8&useUnicode=true&serverTimezone=UTC
    username: root
    password: 1239877Mq..
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
